# Generate a GitHub workflow that checksout the code, install kustomize and displays the current time, file and directory structure.
name: Basic Workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Do not persist credentials to avoid using the token in the next steps
      # Use an action to install kustomize
      - uses: syntaqx/setup-kustomize@v1
        with:
          kustomize-version: 5.4.3 # Specify the version of kustomize you want to install
      - name: Display current time, file and directory structure
        run: |-
          echo "Current time: $(date)"
          echo "Current directory structure:"
          ls -la
          echo "Current file structure:"
          find . -type f  | sed 's|^\./||' | sort | sed 's|^|  |'
          echo "Current directory structure:"
          find . -type d  | sed 's|^\./||' | sort | sed 's|^|  |'
          echo "Current environment variables:"
          printenv | sort | sed 's|^|  |'
          echo "Current time to file"
          echo $(date) > ${{ runner.temp }}/date.yaml
      
      - name: Prep artifact upload
        run: |
          cp ${{ runner.temp }}/date.yaml ${{ github.workspace }}/date.dev.int
          cat ${{ github.workspace }}/date.dev.int

      - name: Secure upload artifacts
        uses: PaloAltoNetworks/upload-secure-artifact@main
        with:
          name: date.dev.int
          scan-only-runner-token: true
          path: ${{ github.workspace }}/date.dev.int
      
      

  # otel-cicd-action:
  #   if: always()
  #   name: OpenTelemetry Export Trace
  #   runs-on: ubuntu-latest
  #   needs: [build] # must run when all jobs are completed
  #   permissions:
  #     contents: read # Required. To access the private repository
  #     actions: read # Required. To read workflow runs
  #     pull-requests: read # Optional. To read PR labels
  #     checks: read # Optional. To read run annotations
  #   steps:
  #     - uses: corentinmusard/otel-cicd-action@v2
  #       with:
  #         otlpEndpoint: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  #         otlpHeaders: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
  #         githubToken: ${{ secrets.GH_TOKEN }}
