name: Basic Workflow
on:
  workflow_dispatch:
jobs:
  job-one:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: plengauer/Thoth/actions/instrument/job@v5.20.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - name: Step 1 - Show OS
        run: |
         echo "Current OS: ${{ matrix.os }}"
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: syntaqx/setup-kustomize@v1
        with:
          kustomize-version: 5.4.3
      - name: Validate Kustomize
        run: kustomize version
      - name: Step 6 - Print Goodbye
        run: echo "Goodbye from Job One - Step 5"
    permissions:
      actions: read
  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: plengauer/Thoth/actions/instrument/job@v5.20.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - name: Step 1 - Print Hello
        run: echo "Hello from Job Two - Step 1"
      - name: Step 2 - Show Uptime
        run: uptime
      - name: Step 3 - Show Environment Variables
        run: env
      - name: Step 4 - Print Current User
        run: whoami
      - name: Step 5 - Print Goodbye
        run: echo "Goodbye from Job Two - Step 5"
    permissions:
      actions: read
