# Generate a GitHub workflow that checksout the code, install kustomize and displays the current time, file and directory structure.
name: Basic Workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  otel:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/Thoth/actions/instrument/workflow@v5.20.0
        with:
          self_monitoring: false
          github_token: ${{ secrets.GH_TOKEN }}
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/Thoth/actions/instrument/job@v5.20.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}"]'
      - name: Checkout code
        uses: actions/checkout@v2
      # Use an action to install kustomize
      - uses: syntaqx/setup-kustomize@v1
        with:
          kustomize-version: 5.4.3 # Specify the version of kustomize you want to install
      - name: Display current time, file and directory structure
        run: |-
          echo "Current time: $(date)"
          echo "Current directory structure:"
          ls -la
          echo "Current file structure:"
          find . -type f  | sed 's|^\./||' | sort | sed 's|^|  |'
          echo "Current directory structure:"
          find . -type d  | sed 's|^\./||' | sort | sed 's|^|  |'
          echo "Current environment variables:"
          printenv | sort | sed 's|^|  |'
    permissions:
      actions: read
