name: 'Deploy OpenTelemetry'

on:
  workflow_dispatch:
  push:
    branches: 
     - main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:
      - uses: plengauer/Thoth/actions/instrument/deploy@v5.16.5
        with:
          action_repository: plengauer/Thoth
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
