name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: [Basic Workflow]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: inception-health/otel-export-trace-action@latest
        with:
          otlpEndpoint: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          githubToken: ${{ secrets.GH_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}