name: Observability
on:
  workflow_run:
    workflows:
      # The name of the workflow(s) that triggers the export
      - "Basic Workflow"
    types: [completed]

jobs:
  otel-cicd-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          githubToken: ${{ secrets.GH_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
          # Add extra attributes to enrich the trace from the workflow_run event and workflow
          extraAttributes: "platform=home-testing,github.repository=${{ github.event.workflow_run.repository.name }},github.workflow=${{ github.event.workflow_run.name }},github.actor=${{ github.event.workflow_run.actor.name }},github.run_number=${{ github.event.workflow_run.run_number }},github.event_name=${{ github.event.workflow_run.event }},github.head_ref=${{ github.event.workflow_run.head_branch }},github.sha=${{ github.event.workflow_run.head_commit.id }},github.run_started_at=${{ github.event.workflow_run.run_started_at }},github.run_url=${{ github.event.workflow_run.html_url }},github.workflow_ref=${{ github.event.workflow_run.head_branch }},github.workflow_sha=${{ github.event.workflow_run.head_commit.id }}"