name: Observability
on:
  workflow_run:
    workflows:
      # The name of the workflow(s) that triggers the export
      - "Basic Workflow"
    types: [completed]

jobs:
  otel-cicd-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          githubToken: ${{ secrets.GH_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
          extraAttributes: "github.repository=${{ github.repository }},github.workflow=${{ github.workflow }},github.run_id=${{ github.run_id }},github.actor=${{ github.actor }},github.event_name=${{ github.event_name }},github.event_path=${{ github.event_path }}"